apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: apiinstances.gateway.mulesoft.com
spec:
  conversion:
    strategy: None
  group: gateway.mulesoft.com
  names:
    kind: ApiInstance
    listKind: ApiInstanceList
    plural: apiinstances
    singular: apiinstance
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            x-kubernetes-preserve-unknown-fields: true
    additionalPrinterColumns:
    - name: Address
      type: string
      description: The ApiInstance adrresss
      jsonPath: .spec.address

