apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: configurations.gateway.mulesoft.com
spec:
  conversion:
    strategy: None
  group: gateway.mulesoft.com
  names:
    kind: Configuration
    listKind: ConfigurationList
    plural: configurations
    singular: configuration
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          specVersion:
            type: string
            default: v1alpha1
          spec:
            x-kubernetes-preserve-unknown-fields: true
  - name: v1beta1
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: object
        properties:
          specVersion:
            type: string
            default: v1beta1
          spec:
            x-kubernetes-preserve-unknown-fields: true