apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: policybindings.gateway.mulesoft.com
spec:
  conversion:
    strategy: None
  group: gateway.mulesoft.com
  names:
    kind: PolicyBinding
    listKind: PolicyBindingList
    plural: policybindings
    singular: policybinding
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            x-kubernetes-preserve-unknown-fields: true
    additionalPrinterColumns:
    - name: Target
      type: string
      description: The target to apply the Policy
      jsonPath: .spec.targetRef.name
    - name: Policy
      type: string
      description: The Policy to apply
      jsonPath: .spec.policyRef.name
