apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: services.gateway.mulesoft.com
spec:
  conversion:
    strategy: None
  group: gateway.mulesoft.com
  names:
    kind: Service
    listKind: ServiceList
    plural: services
    singular: service
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            x-kubernetes-preserve-unknown-fields: true
    additionalPrinterColumns:
    - name: Address
      type: string
      description: The Service adrresss
      jsonPath: .spec.address
