name: bash scripting

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  bash-scripting:
    runs-on: ubuntu-latest

    steps:
      - name: convert to lowercase
        run: |
          UPPER="HELLO"
          lower=$(echo $UPPER | tr 'A-Z' 'a-z')
          echo "lowercase: $lower"

      - name: checkout
        uses: actions/checkout@v4.1.6

      - name: build json
        run: |
          name="Nadeem"
          echo '{}' | jq '.name = "John" | .age = 30 | .city = "New York"' > data.json
          jq '.' data.json
      