name: bash scripting

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  bash-scripting:
    runs-on: ubuntu-latest

    steps:
      - name: convert to lowercase
        run: |
          UPPER="HELLO"
          lower=$(echo $UPPER | tr 'A-Z' 'a-z')
          echo "lowercase: $lower"

      - name: convert dash to underscore
        run: |
          DASH="hello-world"
          underscore=$(echo $DASH | tr '-' '_')
          echo "underscore: $underscore"