name: bash scripting

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  bash-scripting:
    runs-on: ubuntu-latest

    steps:
      - name: convert to lowercase
        run: |
          UPPER="HELLO"
          lower=$(echo $UPPER | tr 'A-Z' 'a-z')
          echo "lowercase: $lower"

      - name: checkout
        uses: actions/checkout@v4.1.6
      - name: use calculate_days.sh
        run: |
          msg=$(bash ./scripts/hello.sh "Nadeem")
          echo "msg: $msg"

          pwd
          ls -l
          ls -l ./scripts