name: bash scripting

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  bash-scripting:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4.1.6
        
      - name: convert to lowercase
        run: |
          UPPER="HELLO"
          lower=$(echo $UPPER | tr 'A-Z' 'a-z')
          echo "lowercase: $lower"

      - name: get current date by calling calculate_days.sh
        run: |
          date=$(bash ./scripts/calculate_days.sh)
          echo "date: $date"

      - name: convert dash to underscore
        run: |
          DASH="hello-world"
          underscore=$(echo $DASH | tr '-' '_')
          echo "underscore: $underscore"

      - name: convert underscore to underscore
        run: |
          DASH="HelloWorld"
          underscore=$(echo $DASH | tr '_' '-' | tr 'A-Z' 'a-z')
          echo "underscore: $underscore"

      - name: check for null
        run: |
          unset str
          if [ -z "$str" ]; then
            echo "$str is empty"
          else
            echo "$str is not empty"
          fi