name: caller

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
    registration-job1:
      uses: ./.github/workflows/create-reg.yml
      with:
        flex-name: "accounts-dev"