name: called-bulk

on:
  workflow_call:
    inputs:
      env:
        type: string
        required: true
      SN:
        type: string
        required: true
        

jobs:
  reuse-job:
    runs-on: ubuntu-latest

    steps:
      - name: print inputs
        run: |
          echo "SN: ${{ inputs.SN }}"
          echo "env: ${{ inputs.env }}"

      - name: checkout
        uses: actions/checkout@v4.1.6

      - name: read config
        run: |

          name=$(jq '.${{inputs.SN}}.name' config.json)
          echo "name: $name"
          

          
          