name: caller

on:
  workflow_dispatch:
  
permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
    registration-job1:
      uses: ./.github/workflows/create-reg.yml
      with:
        obj: "fgw3"
