name: called

on:
  workflow_call:
    # complied with the caller.yml

    inputs:
      bg:
        type: string
        required: true
      env:
        type: string
        required: true

jobs:
  called-job:
    runs-on: ubuntu-latest
    
    steps:

      - name: echo
        run: |
          echo "caller send: ${{ inputs.bg }} ${{ inputs.env }}"

      - name: checkout
        uses: actions/checkout@v4.1.6

      - name: read config
        run: |
          echo "reading config"
          jq . config.json

      - name: search
        run: |
          echo "searching for ${{ inputs.bg }}-${{ inputs.env }}"
          name=${{ inputs.bg }}-${{ inputs.env }}
          renew=$(jq --arg name "$name" '.[$name].renew' config.json)
          echo "renew: $renew"
          
          # iterate over the config.json elements
          for key in $(jq -r 'keys[]' config.json); do
            echo "key: $key"
            if [[ $key == $name ]]; then
              echo "found $key"
              renew2=$(jq --arg key "$key" '.[$key].renew' config.json)
              echo "renew2: $renew2"
              break
            fi
          done