name: called-bulk

on:
  workflow_call:
    inputs:
      env:
        type: string
        required: true
      obj:
        type: number
        required: true
        

jobs:
  reuse-job:
    runs-on: ubuntu-latest

    steps:
      - name: print inputs
        run: |
          echo "obj: ${{ inputs.obj }}"
          echo "env: ${{ inputs.env }}"

      - name: checkout
        uses: actions/checkout@v4.1.6

      - name: read config
        run: |
          echo "reading config"
          jq . config.json

          # iterate over the json objects of the config file
          for key in $(jq -r 'keys[]' config.json); do
            echo "key: $key"
            echo "S.NO: $(jq -r ".$key.S_NO" config.json)"
            echo "NAME: $(jq -r ".$key.NAME" config.json)"
          done

          
          