name: called-bulk

on:
  workflow_call:
    inputs:
      env:
        type: string
        required: true
      obj:
        type: string
        required: true
      env_name:
        type: string
        required: true
        

jobs:
  reuse-job:
    runs-on: ubuntu-latest

    steps:
      - name: print inputs
        run: |
          echo "obj: ${{ inputs.obj }}"
          echo "env: ${{ inputs.env }}"
          echo "env_name: ${{ inputs.env_name }}"
          
          