name: caller

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
    caller-job:
      uses: nk1752/called-caller/.github/workflows/called.yml@main
      with:
        bg: 'foo'
        env: 'bar'