name: called

on:
  workflow_call:
    # complied with the caller.yml

    inputs:
      bg:
        type: string
        required: true
      env:
        type: string
        required: true

jobs:
  called-job:
    runs-on: ubuntu-latest
    
    steps:

      - name: echo
        run: |
          echo "called: ${{ inputs.bg }} ${{ inputs.env }}"
