name: caller bulk

on:
  workflow_dispatch:
  push:
    branches:
      - main
  
permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
    matrix-job:
      strategy:
        matrix:
          env: ["dev", "prod"]
          inputs: ["fgw_1", "fgw_2", "fgw_3"]

      uses: ./.github/workflows/called-bulk.yml
      with:
        env: ${{ matrix.env }}
        inputs: ${{ matrix.inputs }}