name: caller bulk

on:
  workflow_dispatch:
  push:
    branches:
      - main
  
permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
    matrix-job:
      strategy:
        matrix:
          env: ["dev"]
          obj: ["fgw_1", "fgw_2"]
          env_name: ["np-a", "np-b", "np-c"]

      uses: ./.github/workflows/called-bulk.yml
      with:
        env: ${{ matrix.env }}
        obj: ${{ matrix.obj }}
        env_name: ${{ matrix.env_name }}