name: caller bulk

on:
  workflow_dispatch:
  push:
    branches:
      - main
  
permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
    matrix-job:
      strategy:
        matrix:
          env: ["dev"]
          obj: [1, 2]

      uses: ./.github/workflows/called-bulk.yml
      with:
        env: ${{ matrix.env }}
        obj: ${{ matrix.obj }}
        