name: caller bulk

on:
  workflow_dispatch:
  push:

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  business-group:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.6

      - name: parse json
        id: json
        run: |
          for key in $(jq -r 'keys[]' config.json); do
            echo "Key: $key"
            bg=$key
            echo "bg=$bg" >> $GITHUB_OUTPUT       
          done
          
  matrix-job:
    strategy:
      matrix:
        bg: ["RegionsBank", "BP"]
        env: ["qa"]
        env_name: ["np-a", "np-b", "np-z-a", "np-z-b"]
        size: ["small", "large"]
    uses: ./.github/workflows/called-bulk.yml
    with:
      bg: ${{ matrix.bg }}
      env: ${{ matrix.env }}
      env_name: ${{ matrix.env_name }}
      size: ${{ matrix.size }}
