name: caller

on:
  workflow_dispatch:
  # setup cron job
  schedule:
    - cron: '0 0 * * *'
  
permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
    registration-job1:
      uses: ./.github/workflows/create-reg-reusable.yml
      with:
        obj: "fgw_1"
        env: "qa"

    registration-job2:
      uses: ./.github/workflows/create-reg-reusable.yml
      with:
        obj: "fgw_1"
        env: "qa"

    registration-job3:
      uses: ./.github/workflows/create-reg-reusable.yml
      with:
        obj: "fgw_1"
        env: "qa"
