name: called-bulk

on:
  workflow_call:
    inputs:
      env:
        type: string
        required: true
      SN:
        type: string
        required: true
        

jobs:
  reuse-job:
    runs-on: ubuntu-latest

    steps:
      - name: print inputs
        run: |
          echo "SN: ${{ inputs.SN }}"
          echo "env: ${{ inputs.env }}"

      - name: checkout
        uses: actions/checkout@v4.1.6

      - name: read config
        id: json
        run: |
          name=$(jq '.${{inputs.SN}}.name' config.json)
          echo "name: $name"

          if [[ "${{inputs.env}}" == "dev" ]]
          then

            echo "dev"
            env_id=$(jq '.${{inputs.SN}}.DEV' config.json)
            echo "env_id: $env_id"
            echo "env_id=$env_id" >> $GITHUB_OUTPUT
          
          elif [[ "${{inputs.env}}" == "prod" ]]
          then

            echo "prod"
            env_id=$(jq '.${{inputs.SN}}.PROD' config.json)
            echo "env_id: $env_id"
            echo "env_id=$env_id" >> $GITHUB_OUTPUT

          elif [[ "${{inputs.env}}" == "qa" ]]
          then

            echo "qa"
            env_id=$(jq '.${{inputs.SN}}.QA' config.json)
            echo "env_id: $env_id"
            echo "env_id=$env_id" >> $GITHUB_OUTPUT

          else
            echo "Invalid env"
            exit 1
          fi

          echo "env_id: $env_id"
          echo "env_id=$env_id" >> $GITHUB_OUTPUT

      - name: display
        run: |
          echo "env_id: ${{steps.json.outputs.env_id}}"
          
          

          
          