name: called-bulk

on:
  workflow_call:
    inputs:
      env:
        type: string
        required: true
      obj:
        type: string
        required: true
      env_name:
        type: string
        required: true
        

jobs:
  reuse-job:
    runs-on: ubuntu-latest

    steps:
      - name: print inputs
        run: |
          echo "obj: ${{ inputs.obj }}"
          echo "env: ${{ inputs.env }}"
          echo "env_name: ${{ inputs.env_name }}"

      - name: checkout
        uses: actions/checkout@v4.1.6

      - name: read config
        run: |
          echo "reading config"
          jq . config.json

          bg=$(jq -r ".${{inputs.obj}}.name" config.json)
          echo "name: $bg"
          echo "bg=$bg" >> $GITHUB_OUTPUT
          bg_lower=$(jq -r ".${{inputs.obj}}.name | ascii_downcase" config.json)
          echo "name lowercase: $bg_lower"
          env=$(jq -r ".${{inputs.obj}}.env" config.json)
          org_id=$(jq -r ".${{inputs.obj}}.org_id" config.json)
          echo "org_id: $org_id"
          
          
          