name: caller

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
    caller-job1:
      uses: nk1752/called-caller/.github/workflows/create-reg.yml@main
      with:
        flex-name: "accounts-dev"