name: caller bulk

on:
  workflow_dispatch:
  push:
    branches:
      - main
  
permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
    matrix-job:
      strategy:
        matrix:
          bg: ["RegionsBank"]
          env: ["dev", "prod"]

      uses: ./.github/workflows/called-bulk.yml
      with:
        env: ${{ matrix.env }}
        bg: ${{ matrix.bg }}
        env_name: "accounts-test"
        