name: caller

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  
permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
    registration-job1:
      uses: ./.github/workflows/create-reg-reusable.yml
      with:
        obj: "fgw_1"
        env: "dev"
