name: caller bulk

on:
  workflow_dispatch:
  push:
    branches:
      - main
  
permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
    matrix-job:
      strategy:
        matrix:
          env: ["prod", "dev"]
          SN: ["SN_1", "SN_2"]

      uses: ./.github/workflows/called-bulk.yml
      with:
        env: ${{ matrix.env }}
        SN: ${{ matrix.SN }}
        