name: caller

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
    caller-job1:
      uses: nk1752/called-caller/.github/workflows/called.yml@main
      with:
        bg: 'accounts'
        env: 'dev'

    caller-job2:
      uses: nk1752/called-caller/.github/workflows/called.yml@main
      with:
        bg: 'accounts'
        env: 'qa'