name: create registration

on:
  workflow_call:
    inputs:
      flex-name:
        type: string
        required: true

jobs:
  register-renew:
    runs-on: ubuntu-latest
    
    steps:

      - name: echo
        run: |
          echo "caller send: ${{ inputs.flex-name }}"

      - name: checkout
        uses: actions/checkout@v4.1.6

      - name: read config
        run: |
          echo "reading config"
          jq . config.json

      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: pull image
        run: |
          docker pull mulesoft/flex-gateway:latest

      # list docker images
      - name: list docker images
        run: |
          docker images

      # check os version on ubuntu
      - name: check os version
        run: |
          cat /etc/os-release

      - name: make temp directory
        run: |
          mkdir -p temp
          ls -l

      - name: search
        id: search
        run: |
          # iterate over the config.json elements
          for key in $(jq -r 'keys[]' config.json); do
            echo "*************************"
            echo "key: $key"
            echo "*************************"

            oper=$(jq -r --arg key "$key" '.[$key].oper' config.json)
            echo "operation found: $oper"
            
            if [[ $key == ${{inputs.flex-name}} && $oper == "register" ]]
            then  
              echo "register ${{inputs.flex-name}}"
              echo "oper=$oper" >> GITHUB_OUTPUT
              echo "flex-name=$key" >> GITHUB_OUTPUT

              break
            elif [[ $key == ${{inputs.flex-name}} && $oper == "renew" ]]
            then  
              echo "renew registration ${{inputs.flex-name}}"
              echo "oper=$oper" >> GITHUB_OUTPUT
              echo "flex-name=$key" >> GITHUB_OUTPUT

              break
            else
              echo "${{inputs.flex-name}} for operation $oper skipping..."
              echo "oper=none" >> GITHUB_OUTPUT
              
            fi  
              # break
          done # end of for loop

      - name: check variables
        run: |
          cat GITHUB_OUTPUT
          echo "oper=${{steps.search.outputs.oper}}"
          echo "flex-name=${{steps.search.outputs.flex-name}}"

      - name: register
        if: ${{steps.search.outputs.oper}} == 'wait'
        run: |
          echo "registering..."

          flex-name=${{ steps.search.outputs.flex-name }}

          sudo docker run --entrypoint flexctl \
            -v "$(pwd)/temp":/registration -u $UID mulesoft/flex-gateway \
            registration create \
            --client-id=b95726291f564ae2942ac2c4ecc46311 \
            --client-secret=59dB6D7A84bd442bAfE7422233a82902 \
            --environment=2c6f18bb-03e2-4874-a489-7216df5b5bc2 \
            --connected=true \
            --organization=a6ea8ce7-6d5f-41ee-a802-5505e8833854 \
            --output-directory=/registration \
            $flex-name

      - name: renew register
        if: ${{steps.search.outputs.oper}} == 'renew'
        run: |
          echo "renewing..."

      - name: print registration.yaml
        if: ${{steps.search.outputs.oper}} == 'register'
        run: |
          ls -l
          cat ./temp/registration.yaml
          
      - name: cleanup
        run: |
          echo "cleaning up..."
          