name: create registration

on:
  workflow_call:
    inputs:
      flex-name:
        type: string
        required: true

jobs:
  register-renew:
    runs-on: ubuntu-latest

    steps:
      - name: echo
        run: |
          echo "caller send: ${{ inputs.flex-name }}"

      - name: checkout
        uses: actions/checkout@v4.1.6

      - name: read config
        run: |
          echo "reading config"
          jq . config.json

      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: pull image
        run: |
          docker pull mulesoft/flex-gateway:latest

      # list docker images
      - name: list docker images
        run: |
          docker images

      # check os version on ubuntu
      - name: check os version
        run: |
          cat /etc/os-release

      - name: make temp directory
        run: |
          mkdir -p temp
          mkdir -p temp2
          ls -l

      - name: search
        id: search
        run: |
          # iterate over the config.json elements
          for key in $(jq -r '.[$keys_unsorted]' config.json); do

            echo "*************************"
            echo "key: $key"
            echo "*************************"

            oper=$(jq -r --arg key "$key" '.[$key].oper' config.json)

            echo "testing $key:$oper"
            
            if [[ $oper == "register" || $oper == "renew" ]]
            then  
              echo "found match! $oper for $key"
              echo "oper=$oper" >> $GITHUB_OUTPUT
              echo "flex-name=$key" >> $GITHUB_OUTPUT

              break
            fi
            
            echo "skipping $key..."

              # break
          done # end of for loop

      - name: check variables
        run: |
          echo "oper=${{steps.search.outputs.oper}}"
          echo "flex-name=${{steps.search.outputs.flex-name}}"

      - name: check for register 
        if: ${{steps.search.outputs.oper == 'register'}}
        run: |
          echo "registering..."
          echo "oper=${{steps.search.outputs.oper}}"
          echo "flex-name=${{steps.search.outputs.flex-name}}"
          
          
      - name: check for renew 
        if: ${{steps.search.outputs.oper == 'renew'}}
        run: |
          echo "registering..."
          echo "oper=${{steps.search.outputs.oper}}"
          echo "flex-name=${{steps.search.outputs.flex-name}}"
          
      - name: cleanup
        run: |
          echo "cleaning up..."
