name: create registration

on:
  workflow_call:
    # complied with the caller.yml

    inputs:
      bg:
        type: string
        required: true
      env:
        type: string
        required: true

jobs:
  register-renew:
    runs-on: ubuntu-latest
    
    steps:

      - name: echo
        run: |
          echo "caller send: ${{ inputs.bg }} ${{ inputs.env }}"

      - name: checkout
        uses: actions/checkout@v4.1.6

      - name: read config
        run: |
          echo "reading config"
          jq . config.json

      - name: search
        id: search
        run: |
          # iterate over the config.json elements
          for key in $(jq -r 'keys[]' config.json); do
            echo "*************************"
            echo "key: $key"
            echo "*************************"

            oper=$(jq --arg key "$key" '.[$key].oper' config.json)
            echo "operation found: $oper"
            
            if [[ $oper -eq 'register' ]]
            then  
              echo "registering..."
            elif [[ "$oper" -eq "renew" ]]
            then  
              echo "renewing..."
            else
              echo "operation $oper skipping..."
            fi  
              # break
          done # end of for loop

      