name: create registration

on:
  workflow_call:
    inputs:
      obj:
        type: string
        required: true
      env:
        type: string
        required: true
      size:
        type: string
        required: false
        default: "small"
      no:
        type: string
        required: false
        default: "1"

jobs:
  register-renew:
    runs-on: ubuntu-latest

    steps:
      - name: echo
        run: |
          echo "caller send: ${{ inputs.obj }}"

      - name: checkout
        uses: actions/checkout@v4.1.6

      - name: read config
        run: |
          echo "reading config"
          jq . config.json

      - name: parse json
        id: json
        run: |
          echo "bg=$(jq -r '.${{inputs.obj}}.name' config.json)" >> $GITHUB_OUTPUT
          echo "bg_lower=$(jq -r '.${{inputs.obj}}.name' | ascii_downcase" config.json)" >> $GITHUB_OUTPUT
          echo "env=$(jq -r '.${{inputs.obj}}.env' config.json)" >> $GITHUB_OUTPUT
          echo "size=$(jq -r '.${{inputs.obj}}.size | ascii_downcase' config.json)" >> $GITHUB_OUTPUT

          fgw_name='fgw-'$bg_lower-${{inputs.env}}-${{inputs.size}}-${{inputs.no}}
          echo "fgw_name=$fgw_name" >> $GITHUB_OUTPUT

      - name: echo
        run: |
          echo "fgw_name: ${{ steps.json.outputs.fgw_name }}"
          echo "env: ${{ steps.json.outputs.env }}"
          echo "size: ${{ steps.json.outputs.size }}"
          echo "no: ${{ steps.json.outputs.no }}"
