name: create registration

on:
  workflow_call:
    inputs:
      obj:
        type: string
        required: true

jobs:
  register-renew:
    runs-on: ubuntu-latest

    steps:
      - name: echo
        run: |
          echo "caller send: ${{ inputs.obj }}"

      - name: checkout
        uses: actions/checkout@v4.1.6

      - name: read config
        run: |
          echo "reading config"
          jq . config.json

      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: pull image
        run: |
          docker pull mulesoft/flex-gateway:latest

      # list docker images
      - name: list docker images
        run: |
          docker images

      # check os version on ubuntu
      - name: check os version
        run: |
          cat /etc/os-release

      - name: make temp directory
        run: |
          mkdir -p temp
          mkdir -p temp2
          ls -l

      - name: search
        id: search
        run: |
          # iterate over the config.json elements
          for key in $(jq -r 'keys[]' config.json); do
            echo "*************************"
            echo "key: $key"
            echo "*************************"

            oper=$(jq -r --arg key "$key" '.[$key].oper' config.json)
            echo "obj --> ${{inputs.obj}}"
            
            if [[ $key == ${{inputs.obj}} ]]
            then  
              echo "found match! $oper ${{inputs.obj}}"
              echo "oper=$key.oper" >> $GITHUB_OUTPUT
              echo "bg=$key.bg" >> $GITHUB_OUTPUT
              echo "env=$key.env" >> $GITHUB_OUTPUT
              echo "size=$key.size" >> $GITHUB_OUTPUT
              echo "no=$key.no" >> $GITHUB_OUTPUT

              break
            else
              echo "skipping --> ${{inputs.obj}}"
              
              
            fi  
              # break
          done # end of for loop

      - name: check variables
        run: |
          echo oper=${{steps.search.outputs.oper}}
          echo obj=${{steps.search.outputs.obj}}
          echo bg=${{steps.search.outputs.bg}}
          echo env=${{steps.search.outputs.env}}
          echo size=${{steps.search.outputs.size}}
          echo no=${{steps.search.outputs.no}}
              
      - name: check for register 
        if: ${{steps.search.outputs.oper == 'register'}}
        run: |
          echo "registering..."
          echo "oper=${{steps.search.outputs.oper}}"
          echo "flex-name=${{steps.search.outputs.obj}}"
          
          
      - name: check for renew 
        if: ${{steps.search.outputs.oper == 'renew'}}
        run: |
          echo "registering..."
          echo "oper=${{steps.search.outputs.oper}}"
          echo "flex-name=${{steps.search.outputs.obj}}"
          
      - name: cleanup
        run: |
          echo "cleaning up..."
