name: create registration

on:
  workflow_call:
    inputs:
      obj:
        type: string
        required: true
      env:
        type: string
        required: true
      size:
        type: string
        required: false
        default: "small"
      no:
        type: string
        required: false
        default: "1"

jobs:
  register-renew:
    runs-on: ubuntu-latest

    steps:
      - name: echo
        run: |
          echo "caller send: ${{ inputs.obj }}"

      - name: checkout
        uses: actions/checkout@v4.1.6

      - name: read config
        run: |
          echo "reading config"
          jq . config.json

      - name: search
        id: json
        run: |
          # iterate over the config.json elements
          for key in $(jq -r 'keys[]' config.json); do
            echo "*************************"
            echo "key: $key"
            echo "*************************"
            
            if [[ "$key" == ${{inputs.obj}} ]];
            then  
              echo "found match! $oper ${{inputs.obj}}"

              bg=$(jq -r ".$key.name" config.json)
              echo "name: $bg"

              fgw-name=fgw-$bg
              echo "fgw-name: $fgw-name"

              break
            fi  
          done # end of for loop
