name: create registration

on:
  workflow_call:
    inputs:
      obj:
        type: string
        required: true
      env:
        type: string
        required: true
      size:
        type: string
        required: false
        default: "SMall"
      no:
        type: string
        required: false
        default: "1"

jobs:
  register-renew:
    runs-on: ubuntu-latest

    steps:
      - name: echo
        run: |
          echo "caller send: ${{ inputs.obj }}"

      - name: checkout
        uses: actions/checkout@v4.1.6

      - name: read config
        run: |
          echo "reading config"
          jq . config.json

      - name: parse json
        id: json
        run: |
          bg=$(jq -r ".${{inputs.obj}}.name" config.json)
          echo "name: $bg"
          echo "bg=$bg" >> $GITHUB_OUTPUT
          bg_lower=$(jq -r ".${{inputs.obj}}.name | ascii_downcase" config.json)
          echo "name lowercase: $bg_lower"
          env=$(jq -r ".${{inputs.obj}}.env" config.json)

          size=$(echo ${{inputs.size}} | tr '[:upper:]' '[:lower:]')

          fgw_name='fgw-'$bg-${{inputs.env}}-$size-${{inputs.no}}
          echo "fgw_name: $fgw_name"

          echo "fgw_name=$fgw_name" >> $GITHUB_OUTPUT

      - name: echo
        run: |
          echo "fgw_name: ${{ steps.json.outputs.fgw_name }}"
          echo "name: ${{ steps.json.outputs.bg }}"

          echo "### flex name: ${{ steps.json.outputs.fgw_name }}" >> $GITHUB_STEP_SUMMARY

          # convert to lowercase
          BIG_LOWER=$(echo ${{inputs.size}} | tr '[:upper:]' '[:lower:]')
          echo "BIG_LOWER: $BIG_LOWER"