name: dispatch-test

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: select enironment
        options: 
          - dev
          - qa
          - prod
      size:
        type: choice
        description: Which size to use
        options:
          - small
          - medium
          - large
      no:
        type: number
        description: Number of objects to create
        default: 1

  push:
      branches:
        - main

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  json-test:
    runs-on: ubuntu-latest

    steps:

      - name: print inputs
        run: |
          echo "env: ${{ github.event.inputs.env }}"
          echo "size: ${{ github.event.inputs.size }}"
          echo "no: ${{ github.event.inputs.no }}"
          
