name: json testing

on:
  workflow_dispatch:
  push:
      branches:
        - main
 
permissions:
  contents: read
  pull-requests: write
  id-token: write

env:
  obj: "fgw1"

jobs:
  json-test:
    runs-on: ubuntu-latest

    steps:

      - name: checkout
        uses: actions/checkout@v4.1.6

      - name: test -z
        run: |
          jq 'keys' config.json >> keys.json
          jq . keys.json

          test=$(jq '.RegionsBank' config.json)
          echo $test

      - name: test -z
        run: |
          error=$(jq '.error' vault.json)
          echo $error

          if [ -z "$error" ]; then
            echo "error is empty"
          else
            echo "error is not empty"
          fi
      
      - name: test -n
        run: |
          test=$(jq -r '.RegionsBank' config.json)
          echo $test

          if [ -n "$test" ]; then
            echo "test is null or empty"
          else
            echo "test is not null"
          fi

      - name: direct test for null
        run: |
          test=$(jq -r '.ned' config.json)
          echo $test

          if [ "$test" ]; then
            echo "test is NOT null or empty"
          else
            echo "test is null"
          fi

           
      