name: json testing

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  id-token: write

env:
  obj: "fgw1"

jobs:
  json-test:
    runs-on: ubuntu-latest

    steps:
      - name: echo
        run: |
          echo "caller send: ${{ env.obj }}"

      - name: checkout
        uses: actions/checkout@v4.1.6

      - name: check jq
        run: |
          jq --help

      - name: base64 encode registration-old.yaml
        run: |
          yaml64=$(base64 registration-old.yaml)
          
          echo '{
            "reg": "$yaml64"
          }' > payload.json

          jq . payload.json
          