name: json testing

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  id-token: write

env:
  obj: "fgw1"

jobs:
  json-test:
    runs-on: ubuntu-latest

    steps:
      - name: echo
        run: |
          echo "caller send: ${{ env.obj }}"

      - name: checkout
        uses: actions/checkout@v4.1.6

      - name: read config
        run: |
          echo "reading config"
          jq . config.json

      - name: search
        id: search
        run: |
          # iterate over the config.json elements
          for key in $(jq -r 'keys[]' config.json); do
            echo "*************************"
            echo "key: $key"
            echo "*************************"
            
            if [ -z "$key" ]; then
              echo "key is empty"
              continue
            fi

            if [ "$key" == "null" ]; then
              echo "key is null"
              continue
            fi

            if [[ "$key" == ${{env.obj}} ]]; then
              
              # get the value of the key
              oper=$(jq -r ".$key.oper" config.json)
              echo "oper: $oper"
              bg=$(jq -r ".$key.bg" config.json)
              echo "bg: $bg"
              env=$(jq -r ".$key.env" config.json)
              size=$(jq -r ".$key.size" config.json)
              no=$(jq -r ".$key.no" config.json)
            fi

            
          done # end of for loop

      - name: check variables
        run: |
          echo oper=${{steps.search.outputs.oper}}
          echo bg=${{steps.search.outputs.bg}}
          echo env=${{steps.search.outputs.env}}
          echo size=${{steps.search.outputs.size}}
          echo no=${{steps.search.outputs.no}}
