name: json testing

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  id-token: write

env:
  obj: "fgw1"

jobs:
  json-test:
    runs-on: ubuntu-latest

    steps:
      - name: echo
        run: |
          echo "caller send: ${{ env.obj }}"

      - name: checkout
        uses: actions/checkout@v4.1.6

      - name: read config
        run: |
          echo "reading config"
          jq . config.json

      - name: search
        id: search
        run: |
          # iterate over the config.json elements
          for key in $(jq -r 'keys[]' config.json); do
            echo "*************************"
            echo "key: $key"
            echo "*************************"
            
            if [[ $key == ${{env.obj}}]]
            then  
              echo "found match! $oper ${{env.obj}}"

              jq -r .$key.oper config.json

              echo "oper=$(jq -r .$key.oper config.json)" >> $GITHUB_OUTPUT
              echo "bg=$(jq -r .$key.bg config.json)" >> $GITHUB_OUTPUT
              echo "env=$(jq -r .$key.env config.json)" >> $GITHUB_OUTPUT
              echo "size=$(jq -r .$key.size config.json)" >> $GITHUB_OUTPUT
              echo "no=$(jq -r .$key.no config.json)" >> $GITHUB_OUTPUT

              break
            else
              echo "skipping --> ${{env.obj}}"
              
              
            fi  
              # break
          done # end of for loop

      - name: check variables
        run: |
          echo oper=${{steps.search.outputs.oper}}
          echo bg=${{steps.search.outputs.bg}}
          echo env=${{steps.search.outputs.env}}
          echo size=${{steps.search.outputs.size}}
          echo no=${{steps.search.outputs.no}}
