name: json testing

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  id-token: write

env:
  obj: "fgw1"

jobs:
  json-test:
    runs-on: ubuntu-latest

    steps:

      - name: checkout
        uses: actions/checkout@v4.1.6

      - name: read confog.json
        run: |
          jq -r '.[] | key' config.json

      