name: json testing

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: Who to greet
        options: 
          - dev
          - qa
          - prod
      size:
        type: choice
        description: Which size to use
        options:
          - small
          - medium
          - large
      no:
        type: number
        description: Number of objects to create
        default: 1

  push:
      branches:
        - main
 
permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  json-test:
    runs-on: ubuntu-latest

    steps:

      - name: print inputs
        run: |
          echo "env: ${{ github.event.inputs.env }}"
          echo "size: ${{ github.event.inputs.size }}"

      - name: checkout
        uses: actions/checkout@v4.1.6

      - name: read keys
        run: |
          jq 'keys' config.json >> keys.json
          jq . keys.json

      # The -z test checks if a variable is null or an empty string:
      - name: test -z
        run: |
          list_Data=$(jq '.ned' config.json)
          echo $list_Data

          if [[ "$list_Data" == null ]]; then
              echo "null"
              register=true
          else
              echo "not null"
              register=false
          fi

          echo $register

          if [[ "$register" == true ]]; then
              echo "true"
          else
              echo "false"
          fi

      