name: json testing

on:
  workflow_dispatch:
 
permissions:
  contents: read
  pull-requests: write
  id-token: write

env:
  obj: "fgw1"

jobs:
  json-test:
    runs-on: ubuntu-latest

    steps:

      - name: checkout
        uses: actions/checkout@v4.1.6

      - name: read confog.json
        run: |
          jq 'keys' config.json >> keys.json
          jq . keys.json

          test=$(jq '.RegionsBank' config.json)
          echo $test

          error=$(jq '.error' vault.json)
          echo $error

           
      