name: json testing

on:
  workflow_dispatch:
  push:
      branches:
        - main
 
permissions:
  contents: read
  pull-requests: write
  id-token: write

env:
  obj: "fgw1"

jobs:
  json-test:
    runs-on: ubuntu-latest

    steps:

      - name: checkout
        uses: actions/checkout@v4.1.6

      - name: read keys
        run: |
          jq 'keys' config.json >> keys.json
          jq . keys.json

      # The -z test checks if a variable is null or an empty string:
      - name: test -z
        run: |
          test=$(jq '.RegionsBank' config.json)
          echo $test

          if [[ "$test" == "" ]]; then
            echo "test is null or empty"
          else
            echo "test is NOT empty"
          fi

      