name: json testing

on:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  id-token: write

env:
  obj: "fgw1"

jobs:
  json-test:
    runs-on: ubuntu-latest

    steps:
      - name: echo
        run: |
          echo "caller send: ${{ env.obj }}"

      - name: checkout
        uses: actions/checkout@v4.1.6

      - name: check jq
        run: |
          jq --help

      - name: read confog.json
        run: |
          jq . config.json

      - name: base64 iterate
        run: |
          for i in $(jq -r '.[] | @base64' config.json); do
            echo $i | base64 --decode
          done

      - name: iterate over json & print name
        run: |
          for i in $(jq -r '.[] | @base64' config.json); do
            echo $i | base64 --decode | jq -r '.name'
          done