name: json testing

on:
  workflow_dispatch:
  push:
      branches:
        - main
 
permissions:
  contents: read
  pull-requests: write
  id-token: write

env:
  obj: "fgw1"

jobs:
  json-test:
    runs-on: ubuntu-latest

    steps:

      - name: checkout
        uses: actions/checkout@v4.1.6

      - name: read keys
        run: |
          jq 'keys' config.json >> keys.json
          jq . keys.json

      # The -z test checks if a variable is null or an empty string:
      - name: test -z
        run: |
          error=$(jq '.error' config.json)
          echo $error

          if [ -z "$error" ]; then
            echo "error is empty"
          else
            echo "error is not empty"
          fi

      # The -n test checks if a variable is NOT null:
      - name: test -n
        run: |
          test=$(jq -r '.RegionsBank' config.json)
          echo $test

          if [ -n $test ]; then
            echo "test is NOT null or empty"
          else
            echo "test is null or empty"
          fi

      - name: chatGPT
        run: |
          # Example variable
          variable="Hello"

          # Check if the variable is null or empty
          if [ -z "$variable" ]; then
              echo "Variable is null or empty"
          else
              echo "Variable is NOT null"
          fi

          # Change variable value
          variable="Hello"

          # Check again
          if [ -n "$variable" ]; then
              echo "Variable is NOT null"
          else
              echo "Variable is null or empty"
          fi
           
      