name: renew-bulk-reusable

on:
  workflow_call:
    inputs:
      bg:
        type: string
        required: true
      env:
        type: string
        required: true
      env_name:
        type: string
        required: true
      size:
        type: string
        required: false
        default: "small"
      no:
        type: string
        required: false
        default: "1"
        
permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  renew-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: print inputs
        run: |
          echo "bg: ${{ inputs.bg }}"
          echo "env: ${{ inputs.env }}"
          echo "env_name: ${{ inputs.env_name }}"
          echo "size: ${{ inputs.size }}"
          echo "no: ${{ inputs.no }}"

      - name: checkout
        uses: actions/checkout@v4.1.6

      - name: parse json for environment
        id: json
        run: |             
          bg=${{inputs.bg}}
          echo "bg=$bg" >> $GITHUB_OUTPUT
          
          bg_lower=$(echo $bg | tr 'A-Z' 'a-z')
          echo "bg_lower=$bg_lower" >> $GITHUB_OUTPUT

          env_name=$(echo ${{inputs.env_name}} | tr 'A-Z' 'a-z')
          echo "env_name=$env_name" >> $GITHUB_OUTPUT

          env=$(echo ${{inputs.env}} | tr 'A-Z' 'a-z')
          echo "env=$env" >> $GITHUB_OUTPUT

          env_id=$(jq -r '.${{inputs.bg}}.${{inputs.env}}' config.json)
          echo "env_id=$env_id_dev" >> $GITHUB_OUTPUT

          fgw_name='fgw-'$bg_lower-$env_name-${{inputs.size}}-${{inputs.no}}
          echo "fgw_name: $fgw_name"
          echo "fgw_name=$fgw_name" >> $GITHUB_OUTPUT

      - name: print variables
        run: |
          echo "fgw_name: ${{ steps.json.outputs.fgw_name }}"
          echo "bg: ${{ steps.json.outputs.bg }}"
          echo "env: ${{ steps.json.outputs.env }}"
          echo "env_name: ${{ steps.json.outputs.env_name }}"
          echo "env_id: ${{ steps.json.outputs.env_id }}"
          echo "size: ${{ inputs.size }}"
          echo "no: ${{ inputs.no }}"
          echo "## flex name: ${{ steps.json.outputs.fgw_name }}" >> $GITHUB_STEP_SUMMARY

      - name: pull secrets from vault
        run: |
          echo "pull secrets from vault"         

      - name: inspect flex registration
        run: |
          docker run --entrypoint flexctl \
            -v "$(pwd)/temp":/registration \
            -u $UID mulesoft/flex-gateway \
            registration inspect --file=/registration/registration.yaml > reg-date.json

          jq . reg-date.json

      - name: renew registration
        run: |
          sudo docker run --entrypoint flexctl \
            -v "$(pwd)":/renew \
            -v "$(pwd)/temp":/registration \
            -u $UID mulesoft/flex-gateway \
            registration renew \
            --client-id=b95726291f564ae2942ac2c4ecc46311 \
            --client-secret=59dB6D7A84bd442bAfE7422233a82902 \
            --output-directory=/renew \
            /registration/registration.yaml