name: renew-bulk

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  business-group:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.json.outputs.bg_matrix }}
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.6

      - name: parse json
        id: json
        run: |
          jq 'keys' config.json >> bg.json
          echo "bg_matrix=$(jq . bg.json) >> $GITHUB_OUTPUT

  # This job will be called by the caller-bulk.yml workflow using matrix strategy
  # The matrix will be output from the business-group job
  # The matrix will be used to call the called-bulk.yml workflow
  renew-matrix:
    needs: business-group
    strategy:
      matrix:
        bg: ${{fromJson(needs.business-group.outputs.matrix)}}
        env: ["DEV"]
        env_name: ["dev"]

    uses: ./.github/workflows/renew-bulk-reusable.yml
    with:
      bg: ${{ matrix.bg }}
      env: "DEV"
      env_name: "dev"
    