name: vault

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  # Use docker.io for Docker Hub if empty
  RENEW: true
  ID: 1
  NAME: "rashida"
  BG: "blue"
  ENV: "dev"

jobs:
  Variables:
    
    runs-on: ubuntu-latest
    permissions:
      contents: read # read|write|none
      id-token: write # read|write|none
      
    steps:
      # - name: pull secrets from vault
      #   id: vault
      #   uses: hashicorp/vault-action@v3.0.0
      #   with:
      #     url: "${{ secrets.VAULT_ADDR }}"
      #     token: "${{ secrets.VAULT_TOKEN }}"
      #     namespace: "admin"
      #     secrets: |
      #       secret/data/poc/secret1 nadeem | nadeem
      
      - uses: eLco/setup-vault@v1
        with:
          vault_version: "1.12.0"
          
      - name: read secrets using approle
        run: |
          VAULT_ADDR="https://nk1752-cluster-public-vault-55c83db1.9e78ed07.z1.hashicorp.cloud:8200";
          VAULT_NAMESPACE="admin"

          VAULT_TOKEN=$(curl -s --header "X-Vault-Namespace: $VAULT_NAMESPACE" \
            --request POST --data '{"role_id": "10e4832f-e504-1732-97d2-5aa1410c9c81", "secret_id": "9ff611aa-0856-8117-3cd2-4d7d62cccee3"}' \
            $VAULT_ADDR/v1/auth/approle/login | jq -r '.auth.client_token' )

          curl -s --header "X-Vault-Token: $VAULT_TOKEN" \
            --header "X-Vault-Namespace: $VAULT_NAMESPACE" \
            $VAULT_ADDR/v1/secret/data/sample-secret | jq -r ".data"

          echo "write secret using CLI"
          vault kv put secret/test/webapp api-key="ABC0DEFG9876"

          
          tee payload.json <<EOF
          {
            "data": {
              "api-key": "ABC0DEFG9876"
            }
          }
          EOF

          curl --header "X-Vault-Token: $VAULT_TOKEN" \
            --header "X-Vault-Namespace: admin" \
            --data @payload.json \
            $VAULT_ADDR/v1/secret/data/test/webapp | jq -r ".data"

