name: vault

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

env:
  # Use docker.io for Docker Hub if empty
  RENEW: true
  ID: 1
  NAME: "rashida"
  BG: "blue"
  ENV: "dev"

jobs:
  Variables:
    
    runs-on: ubuntu-latest
    permissions:
      contents: read # read|write|none
      id-token: write # read|write|none
      
    steps:
      - name: pull secrets from vault
        id: vault
        uses: hashicorp/vault-action@v3.0.0
        with:
          url: "${{ secrets.VAULT_ADDR }}"
          token: "${{ secrets.VAULT_TOKEN }}"
          method: "write"
          namespace: "admin"
          secrets: |
            nadeem="nadeem" secret/data/poc/secret1
      
      - uses: eLco/setup-vault@v1
        with:
          vault_version: "1.12.0"
          
      - name: kv2 read
        run: |
          vault kv --help 
          vault kv get secret/data/poc/secret1

          
      